# Generated by Django 6.1 on 2026-09-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_id_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
